<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>Account Report</title>

    <style>
        @page {
            margin: 2mm;
            size: auto;
        }

        html,
        body {
            margin: 0;
            padding: 0;
            font-family: "Courier New", monospace;
            font-size: 10px;
            background: #fff;
            color: #000;
        }

        .report {
            width: 58mm;
            margin: 0;
            padding: 2mm;
            box-sizing: border-box;
        }

        .title {
            text-align: center;
            font-size: 16px;
            font-weight: bold;
            letter-spacing: 1px;
        }

        .subtitle {
            text-align: center;
            font-size: 10px;
            font-weight: bold;
            margin-bottom: 2px;
        }

        .section-title {
            text-align: center;
            font-size: 11px;
            font-weight: bold;
            margin: 4px 0 2px;
        }

        .line {
            border-top: 1px dashed #000;
            margin: 3px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        td {
            padding: 1px 0;
            vertical-align: top;
            font-size: 10px;
        }

        .left {
            text-align: left;
        }

        .right {
            text-align: right;
        }

        .center {
            text-align: center;
        }

        .footer {
            text-align: center;
            margin-top: 5px;
            font-size: 10px;
        }

        @media print {
            .report {
                width: 58mm;
            }
        }
    </style>

</head>

<body>

    <div class="report">

        <div class="title">RWINLOT</div>

        <div class="subtitle">ACCOUNT SUMMARY REPORT</div>

        <div class="line"></div>

        <table>

            <tr>
                <td><strong>Retailer</strong></td>
                <td class="right">{{ strtoupper($auth->username) }}</td>
            </tr>

            <tr>
                <td>From</td>
                <td class="right">{{ \Carbon\Carbon::parse($dateFrom)->format('d-m-Y') }}</td>
            </tr>

            <tr>
                <td>To</td>
                <td class="right">{{ \Carbon\Carbon::parse($dateTo)->format('d-m-Y') }}</td>
            </tr>

            <tr>
                <td>Printed</td>
                <td class="right">{{ now()->format('d-m-Y h:i A') }}</td>
            </tr>

        </table>

        <div class="line"></div>

        <div class="section-title">REPORT - 1</div>

        <table>

            <tr style="font-weight: bold;">
                <td class="left">Description</td>
                <td class="right">Amount</td>
            </tr>

            <tr>
                <td colspan="2">
                    <div class="line"></div>
                </td>
            </tr>

            <tr>
                <td>Play Point</td>
                <td class="right">{{ number_format($report1['play_point'], 2) }}</td>
            </tr>

            <tr>
                <td>Commission</td>
                <td class="right">{{ number_format($report1['commission'], 2) }}</td>
            </tr>

            <tr>
                <td>Win Point</td>
                <td class="right">{{ number_format($report1['win_point'], 2) }}</td>
            </tr>

            <tr style="font-weight: bold;">
                <td>Net</td>
                <td class="right">
                    {{ $report1['net'] < 0 ? '-' : '' }}{{ number_format(abs($report1['net']), 2) }}
                </td>
            </tr>

        </table>

        <div class="line"></div>

        <div class="section-title">REPORT - 2</div>

        <table>

            <tr style="font-weight: bold;">
                <td class="left">Description</td>
                <td class="right">Amount</td>
            </tr>

            <tr>
                <td colspan="2">
                    <div class="line"></div>
                </td>
            </tr>

            <tr>
                <td>Play Amount</td>
                <td class="right">{{ number_format($report2['play_point'], 2) }}</td>
            </tr>

            <tr>
                <td>Win Amount</td>
                <td class="right">{{ number_format($report2['win_point'], 2) }}</td>
            </tr>

            <tr style="font-weight: bold;">
                <td>Net</td>
                <td class="right">
                    {{ $report2['net'] < 0 ? '-' : '' }}{{ number_format(abs($report2['net']), 2) }}
                </td>
            </tr>

        </table>

        <div class="line"></div>

        <div class="footer">

            <strong>THANK YOU</strong>

            <br>

            Generated By RWINLOT

        </div>

    </div>

    <script>
        window.onload = function() {
            window.print();
        };
    </script>

</body>

</html>
